spring:
  datasource:

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update  # ??? ?? ??
    show-sql: true      # SQL ?? ??

    properties:
      hibernate:
        format_sql: true  # SQL pretty print